export const CURRENCIES: { code: string; name: string; symbol: string }[] = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
];

export const NATIONALITIES: { code: string; name: string }[] = [
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "IN", name: "India" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "JP", name: "Japan" },
  { code: "CN", name: "China" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "SG", name: "Singapore" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "ZA", name: "South Africa" },
  { code: "NG", name: "Nigeria" },
  { code: "EG", name: "Egypt" },
  { code: "KR", name: "South Korea" },
  { code: "TR", name: "Turkey" },
  { code: "RU", name: "Russia" },
  { code: "ID", name: "Indonesia" },
  { code: "TH", name: "Thailand" },
  { code: "MY", name: "Malaysia" },
  { code: "PH", name: "Philippines" },
  { code: "VN", name: "Vietnam" },
  { code: "PK", name: "Pakistan" },
  { code: "BD", name: "Bangladesh" },
  { code: "LK", name: "Sri Lanka" },
  { code: "NL", name: "Netherlands" },
  { code: "ES", name: "Spain" },
  { code: "IT", name: "Italy" },
  { code: "PT", name: "Portugal" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "FI", name: "Finland" },
  { code: "DK", name: "Denmark" },
  { code: "PL", name: "Poland" },
  { code: "IE", name: "Ireland" },
  { code: "CH", name: "Switzerland" },
  { code: "NZ", name: "New Zealand" },
];

export const CUSTOM_CURRENCY_SYMBOLS: Record<string, string> =
  CURRENCIES.reduce(
    (acc, c) => {
      acc[c.code] = c.symbol;
      return acc;
    },
    {} as Record<string, string>
  );

export const LANGUAGES: { code: string; name: string; nativeName: string }[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
];

export const DEFAULT_EXPENSE_CATEGORIES = [
  { name: "Food & Dining", icon: "utensils", color: "#FF6B4A" },
  { name: "Transport", icon: "car", color: "#6C5CE7" },
  { name: "Shopping", icon: "shopping-bag", color: "#F59E0B" },
  { name: "Housing", icon: "home", color: "#10B981" },
  { name: "Utilities", icon: "zap", color: "#3B82F6" },
  { name: "Entertainment", icon: "film", color: "#EC4899" },
  { name: "Health", icon: "heart-pulse", color: "#EF4444" },
  { name: "Education", icon: "book-open", color: "#8B5CF6" },
  { name: "Travel", icon: "plane", color: "#14B8A6" },
  { name: "Subscriptions", icon: "refresh-cw", color: "#6366F1" },
  { name: "Personal Care", icon: "sparkles", color: "#F472B6" },
  { name: "Other", icon: "more-horizontal", color: "#9CA3AF" },
] as const;

export const DEFAULT_INCOME_CATEGORIES = [
  { name: "Salary", icon: "briefcase", color: "#10B981" },
  { name: "Freelance", icon: "laptop", color: "#6C5CE7" },
  { name: "Business", icon: "store", color: "#3B82F6" },
  { name: "Investments", icon: "trending-up", color: "#F59E0B" },
  { name: "Gifts", icon: "gift", color: "#EC4899" },
  { name: "Other Income", icon: "plus-circle", color: "#8B5CF6" },
] as const;

export const ACCOUNT_ICONS = {
  cash: "banknote",
  bank: "landmark",
  card: "credit-card",
} as const;

export const ACCOUNT_COLORS = [
  "#6C5CE7",
  "#FF6B4A",
  "#10B981",
  "#3B82F6",
  "#F59E0B",
  "#EC4899",
  "#8B5CF6",
  "#14B8A6",
] as const;

export const CATEGORY_COLORS = [
  "#6C5CE7",
  "#FF6B4A",
  "#10B981",
  "#3B82F6",
  "#F59E0B",
  "#EC4899",
  "#8B5CF6",
  "#14B8A6",
  "#EF4444",
  "#6366F1",
  "#F472B6",
  "#9CA3AF",
  "#84CC16",
  "#F97316",
  "#0EA5E9",
] as const;

export const CATEGORY_ICONS = [
  "utensils",
  "car",
  "shopping-bag",
  "home",
  "zap",
  "film",
  "heart-pulse",
  "book-open",
  "plane",
  "refresh-cw",
  "sparkles",
  "more-horizontal",
  "briefcase",
  "laptop",
  "store",
  "trending-up",
  "gift",
  "plus-circle",
] as const;
