/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        // Light palette
        background: '#F6F6F6',
        surface: '#FFFFFF',
        'surface-elevated': '#FFFFFF',
        'surface-sunken': '#EFEFEF',
        border: '#E4E4E7',
        'border-strong': '#D4D4D8',
        content: '#18181B',
        'content-secondary': '#52525B',
        'content-muted': '#8B8B94',
        primary: '#4F46E5',
        'primary-hover': '#4338CA',
        'primary-soft': '#EEF2FF',
        income: '#059669',
        'income-soft': '#ECFDF5',
        expense: '#DC2626',
        'expense-soft': '#FEF2F2',
        transfer: '#0284C7',
        'transfer-soft': '#F0F9FF',
        warning: '#D97706',
        'warning-soft': '#FFFBEB',
        danger: '#DC2626',
        'danger-soft': '#FEF2F2',
        success: '#059669',
        'success-soft': '#ECFDF5',
        overlay: 'rgba(24,24,27,0.45)',
        // camelCase mirrors: the screens style with `bg-primarySoft` style
        // utilities, and Tailwind only emits classes it finds written exactly
        // as they appear here.
        contentSecondary: '#52525B',
        contentMuted: '#8B8B94',
        borderStrong: '#D4D4D8',
        surfaceElevated: '#FFFFFF',
        surfaceSunken: '#EFEFEF',
        primaryHover: '#4338CA',
        primarySoft: '#EEF2FF',
        incomeSoft: '#ECFDF5',
        expenseSoft: '#FEF2F2',
        transferSoft: '#F0F9FF',
        warningSoft: '#FFFBEB',
        dangerSoft: '#FEF2F2',
        successSoft: '#ECFDF5',
      },
      borderRadius: {
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '28px',
        '3xl': '32px',
        pill: '999px',
      },
      spacing: {
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        3.5: '14px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        11: '44px',
        12: '48px',
        14: '56px',
        16: '64px',
        20: '80px',
        24: '96px',
        32: '128px',
      },
      fontSize: {
        // Line heights must carry a unit: a bare number is emitted as a
        // unitless `line-height`, which browsers multiply by the font size
        // (16px * 22 = 352px) and turn every <input> into a giant overlay.
        '2xs': ['10px', { lineHeight: '14px' }],
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '22px' }],
        lg: ['18px', { lineHeight: '24px' }],
        xl: ['20px', { lineHeight: '26px' }],
        '2xl': ['24px', { lineHeight: '30px' }],
        '3xl': ['30px', { lineHeight: '36px' }],
        '4xl': ['36px', { lineHeight: '42px' }],
        '5xl': ['44px', { lineHeight: '50px' }],
      },
    },
  },
  plugins: [],
};